spring:
  application:
    name: ecommerce service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-db
    username: postgres
    password: root

server:
  servlet:
    context-path: /ecommerce

error:
  code:
    1000:
      httpStatus: BAD_REQUEST
      code: ECOM_1000
      title: Bad Request
      detail: Bad Request