spring:
  application:
    name: ecommerce service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-db
    username: postgres
    password: root
    initialization-mode: always
    initialize: true
    continue-on-error: true